blank_issues_enabled: false
contact_links:
  - name: ❗️ All other issues
    url: mailto:reinaldy.rafli@arcet.id
    about: |
      Please contact the developer directly for other issues and asking questions.
